In [4]:
import pandas as pd
from card import ActionType

In [5]:
df = pd.read_csv("../data/cards.csv", sep="|")

In [6]:
df.drop(columns=["tag"], inplace=True)

In [7]:
df

,id,type,category,name,description,effect
0,1,Chance,move,Advance to Go,Collect $200.,0
1,2,Chance,move,Advance to Illinois Ave.,If you pass Go - collect $200.,24
2,3,Chance,move,Advance to St. Charles Place,If you pass Go - collect $200.,11
3,4,Chance,move_utility,Advance to nearest Utility,"If Utility is unowned, you may buy it from the...",10
4,5,Chance,move_rr,Advance to nearest Railroad,"If Railroad is unowned, you may buy it from th...",2
5,6,Chance,move_rr,Advance to nearest Railroad,"If Railroad is unowned, you may buy it from th...",2
6,7,Chance,money,Bank pays you dividend of $50,You gain $50.,50
7,8,Chance,item,Get out of Jail Free,"This card may be kept until needed, or traded/...",0
8,9,Chance,move_abs,Go Back 3 Spaces,You move back 3 spaces.,-3
9,10,Chance,move_jail,Go to Jail,"Do not pass Go, do not collect $200.",10
10,11,Chance,money_houses,Make General Repairs,"For each house you own, you pay $25 - For each...",0
11,12,Chance,money,Pay poor tax of $15,Pay $15.,-15
12,13,Chance,move,Take a trip to Reading Railroad,If you pass Go - collect $200.,5
13,14,Chance,move,Take a walk on the Boardwalk,Advance token to Boardwalk.,39
14,15,Chance,money_players,You have been elected Chairman of the Board,Pay each player $50.,-50
15,16,Chance,money,Your building and loan matures,Collect $150.,150
16,17,Chance,money,You have won a crossword competition,Collect $100.,100
17,18,Community Chest,move,Advance to Go,Collect $200.,0
18,19,Community Chest,money,Bank error in your favor,Collect $200.,200
19,20,Community Chest,money,Doctor's Fees,Pay $50.,-50
20,21,Community Chest,money,From sale of stock you get $50,Collect $50.,50
21,22,Community Chest,item,Get out of Jail Free,"This card may be kept until needed, or traded/...",0
22,23,Community Chest,move_jail,Go to Jail,"Do not pass Go, do not collect $200.",10
23,24,Community Chest,money_players,Grand Opera Night,Collect $50 from every player for opening nigh...,50
24,25,Community Chest,money,Holiday Fund matures,Receive $100.,100
25,26,Community Chest,money,Income Tax Refund,Collect $20.,20
26,27,Community Chest,money_players,It is your Birthday,Collect $10 from each player.,10
27,28,Community Chest,money,Life Insurance Matures,Collect $100.,100
28,29,Community Chest,money,Pay hospital fees of $100,Pay $100.,-100
29,30,Community Chest,money,Pay school fees of $150,Pay $150.,-150
30,31,Community Chest,money,Receive $25 consultancy fee,Collect $25,25
31,32,Community Chest,money_houses,Assessed for street repairs,You are assessed for street repairs - $40 per ...,0
32,33,Community Chest,money,You have won second prize in a beauty contest,Collect $10,10
33,34,Community Chest,money,You inherit $100,Collect $100,100

In [8]:
df_chance = df[df["type"] == "Chance"]
df_community = df[df["type"] == "Community Chest"].reset_index()

In [9]:
df_community

,index,id,type,category,name,description,effect
0,17,18,Community Chest,move,Advance to Go,Collect $200.,0
1,18,19,Community Chest,money,Bank error in your favor,Collect $200.,200
2,19,20,Community Chest,money,Doctor's Fees,Pay $50.,-50
3,20,21,Community Chest,money,From sale of stock you get $50,Collect $50.,50
4,21,22,Community Chest,item,Get out of Jail Free,"This card may be kept until needed, or traded/...",0
5,22,23,Community Chest,move_jail,Go to Jail,"Do not pass Go, do not collect $200.",10
6,23,24,Community Chest,money_players,Grand Opera Night,Collect $50 from every player for opening nigh...,50
7,24,25,Community Chest,money,Holiday Fund matures,Receive $100.,100
8,25,26,Community Chest,money,Income Tax Refund,Collect $20.,20
9,26,27,Community Chest,money_players,It is your Birthday,Collect $10 from each player.,10
10,27,28,Community Chest,money,Life Insurance Matures,Collect $100.,100
11,28,29,Community Chest,money,Pay hospital fees of $100,Pay $100.,-100
12,29,30,Community Chest,money,Pay school fees of $150,Pay $150.,-150
13,30,31,Community Chest,money,Receive $25 consultancy fee,Collect $25,25
14,31,32,Community Chest,money_houses,Assessed for street repairs,You are assessed for street repairs - $40 per ...,0
15,32,33,Community Chest,money,You have won second prize in a beauty contest,Collect $10,10
16,33,34,Community Chest,money,You inherit $100,Collect $100,100

In [10]:

def init_list(active_df: pd.DataFrame) -> list:
    output = []
    for x in range(active_df.shape[0]):
        net = active_df.loc[x, "effect"]
        shared = active_df.loc[x, "category"] == "money_player"
        move_to = ""
        if "Advance to " in str(active_df.loc[x, "name"]):
            statement = (active_df.loc[x, "name"])
            if "nearest " in statement:
                move_to = statement[len("Advance to nearest "):]
            else:
                move_to = statement[len("Advance to "):]
            if "Jail" in move_to:
                move_to = "Jail"

            if move_to[-1] == ".":
                move_to = move_to[:-1]

        set_status = ""

        if "Jail" in str(active_df.loc[x, "name"]) != -1:
            set_status = "in jail"

        output.append(ActionType(net, shared, move_to, set_status))
    return output

In [11]:
chances = init_list(df_chance)
community = init_list(df_community)

In [12]:
print(*community)

        | Net: 0
        | Shared: False
        | Move To: Go
        | Status:

        | Net: 200
        | Shared: False
        | Move To:
        | Status:

        | Net: -50
        | Shared: False
        | Move To:
        | Status:

        | Net: 50
        | Shared: False
        | Move To:
        | Status:

        | Net: 0
        | Shared: False
        | Move To:
        | Status: in jail

        | Net: 10
        | Shared: False
        | Move To:
        | Status: in jail

        | Net: 50
        | Shared: False
        | Move To:
        | Status:

        | Net: 100
        | Shared: False
        | Move To:
        | Status:

        | Net: 20
        | Shared: False
        | Move To:
        | Status:

        | Net: 10
        | Shared: False
        | Move To:
        | Status:

        | Net: 100
        | Shared: False
        | Move To:
        | Status:

        | Net: -100
        | Shared: False
        | Move To:
        | Status:

        | Net: -150
        | Shared: False
        | Move To:
        | Status:

        | Net: 25
        | Shared: False
        | Move To:
        | Status:

        | Net: 0
        | Shared: False
        | Move To:
        | Status:

        | Net: 10
        | Shared: False
        | Move To:
        | Status:

        | Net: 100
        | Shared: False
        | Move To:
        | Status: